export const FETCH_NOTIFICATION_ACTION = "FETCH_NOTIFICATION_ACTION"
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS"
export const FETCH_NOTIFICATION_ERROR = "FETCH_NOTIFICATION_ERROR"
